= iSAQB Advanced Level curriculum for EMBEDDED – Dependable Embedded Systems

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-embedded/workflows/CI%20-%20Releases%20and%20Main/badge.svg["CI - Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-embedded/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-embedded.svg["Contributors",link="https://github.com/isaqb-org/curriculum-embedded/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-embedded.svg["Issues",link="https://github.com/isaqb-org/curriculum-embedded/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-embedded.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-embedded/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the iSAQB Advanced Level curriculum for *EMBEDDED - Dependable Embedded Systems* in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request


== How to build the documents

Prerequisite: You need a Java Runtime(tm) (17 or higher) installed.

You build the output documents via `./gradlew buildDocs`.
That will produce both pdf and html output in English (EN).

== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by Ulrich Becker.
It was forked from https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
