=== {learning-goals}

// tag::DE[]
// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: Fundamental terms of dependable and safety-related systems

Understand the following terms and how they are related to each other:
dependability, safety, availability, reliability, fault tolerance, security,
fault, error, failure, redundancy, replication, freedom from interference,
spatial interference, temporal interference, communication interference,
fail-stop, fail-operational, fail-silent, fail-stop, fail-consistent


[[LG-3-2]]
==== LG 3-2: Developing safety-related systems

Participants understand the fundamental approach to develop a safety-related
system:

* Perform a hazard and risk analysis

* Decide on a risk treatment (mitigate, eliminate, transfer or accept)

* Define and allocate safety requirements

* Realize safety requirements on system, hardware and software level

* Analyze the system's residual risk, e.g. with FMEA and FTA, to verify that
  an acceptable level of risk has been achieved

Participants understand that functional safety must be considered on the system
level, and impacts system architecture, software architecture, and hardware
architecture.

Participants understand the influence of standards in the development of
safety-related systems.

Participants understand the difference in approach to safety-related system
development of standards such as the IEC 61508, ISO 26262, ISO 62304 and other
domain-specific safety standards.


[[LG-3-3]]
==== LG 3-3: Safety classification of requirements and building blocks

Participants understand the process of safety classification:

* Based on the risk analysis, risks are classified regarding their severity
  (e.g., a Safety Integrity Level in IEC 61508).

* The classification of a risk is propagated to safety goals and/or safety
  requirements that are defined to control the risk, and further propagated to
  derived safety requirements and to the building blocks to which a safety
  requirement is allocated.

* Spatial and temporal coupling between building blocks can lead to interference
  between building blocks and to a propagation of the associated risk.

* By decomposing a building block, its associated risk can be distributed over
  and encapsulated in multiple building blocks. This can lead to a lower risk
  classification for the indiviual building blocks. To do so, freedom from
  interference must to be ensured between them.

* The details of safety classification and decomposition are subject to specific
  norms and standards.


[[LG-3-4]]
==== LG 3-4: Tight relationship between system, software and hardware development

Participants understand that system development, software development and
hardware development are closely intertwined when developing dependable and
safety-related systems. For example, software plays a critical role in
diagnosing hardware failures, and hardware plays a critical role in ensuring
freedom of interference between software units.


[[LG-3-5]]
==== LG 3-5: Developing fault-tolerant systems

Participants understand fundamental concepts and activities for developing
fault-tolerant systems and how they interact with each other:

* Fault prevention is concerned with reducing the number of faults that are
  present in a system (e.g., by applying design methodologies or performing
  reviews).

* It is not possible to completely prevent the introduction of faults, therefore
  a fault-tolerant system needs to be able to handle unanticipated errors.

* A fault-tolerant system needs to detect errors and then perform error recovery
  or error mitigation to prevent error propagation. The propagation of
  undetected or unhandled errors may lead to system failure.

* The externally observable behavior of component in the event of an error can
  be classified as fail-stop, fail-operational, fail-silent or fail-consistent
  behavior.

* Redundancy can help to build fault-tolerant systems. Homogeneous and
  heterogeneous approaches exist. Depending on the types of errors to handle, a
  suitable redundancy approach or a combination of approaches has to be
  selected.

[[LG-3-6]]
==== LG 3-6: Architectural patterns and techniques

Participants can apply architectural patterns and techniques for developing
fault-tolerant and safety-related systems:

* Participants can distinguish between structural, functional, informational and
  temporal redundancy.

* Participants know replication as a means to achieve structural
  redundancy. Replication is applied to an architectural building
  block. Therefore, the sphere of replication has to be aligned with
  architectural building blocks. Strong cohesion and loose coupling principles
  have to be taken into consideration for that. The sphere of replication is
  also assigned to an isolation zone with respect to memory regions (i.e.,
  address spaces) and control flows (i.e., threads).

* Participants can select and apply architectural patterns and techniques to
  achieve fault tolerance and know advantages, disadvantages and limitations of
  these patterns.

* Participants know examples of architectural patterns and techniques, such as
  Units of Mitigation, Escalation, Fault Observer, Process-Level Redundancy,
  Ground State, Cold/Warm/Hot Standby, Triple-Modular Redundancy, Duo-Duplex
  Redundancy, Centralized vs. Distributed Voting, N-Version Programming,
  Recovery Blocks, Correcting Audits, Software Update, Software- and
  Hardware-based memory protection techniques.

* Participants can determine the increase in reliability gained by introducing
  redundancy. They are aware of the importance of replicate reliability.

* Participants understand that even after introducing redundancy, single-points
  of failure may remain. They know techniques for hardening these, such as
  control-flow protection.

* Participants understand what common-mode failures are and know sources of
  common-mode failures.

* Participants know techniques for testing hardened systems, such as fault
  injection.


[[LG-3-7]]
==== LG 3-7: Approaches to fault prevention

Participants understand that suitable processes and methods for design,
implementation, verification, and testing are crucial to prevent faults in the
system.

Participants know that in a safety-related system, norms and standards give
recommendations for processes and methods.


[[LG-3-8]]
==== LG 3-8: Patterns for detecting errors and failures

Participants an select and apply patterns and techniques such as Checksum,
Parameter Checking, Heartbeat, Leaky Bucket Counter, System Monitor, Watchdog,
Plausibility Checks, Control Flow Monitoring.

Participants can select and apply detection patterns that are used with
redundancy such as Voting, Lockstep.

Participants understand the importance of timely error detection.


[[LG-3-9]]
==== LG 3-9: Patterns for error recovery

Patterns can select and apply patterns for error recovery such as Data Reset,
Error Handler, Failover, Retries, Limiting Retries, Quarantine, Deactivation,
Restart, Return to Reference Point, Rollback, Roll-Forward.

[[LG-3-10]]
==== LG 3-10: Patterns for error mitigation

Participants can select and apply patterns for error mitigation such as Error
Correcting Codes and Marked Data.


// end::EN[]
