=== {learning-goals}


// tag::DE[]
// end::DE[]

// tag::EN[]
[[LG-8-1]]
==== LG 8-1: Distribution of functionalities in distributed or multi-core system architectures

Understand the process of distributing functionalities in a distributed and/or multi-core system architecture:

* Identifying the units of distribution

* Analyzing the communication patterns between the units of distribution

* Performing the tradeoff between efficient communication and isolation:
Functionalities that interact intensively should be collocated, whereas for
safety or reliability reasons certain functionalities should be isolated from
each other.

* Allocating the units of distribution to individual cores (for multi-core) or
devices (Electronic Control Units (ECUs)) according to these tradeoffs


[[LG-8-2]]
==== LG 8-2: Basics of multi-core development for embedded systems

Understand the motivation for using multi-core systems: increased processing
power and stronger isolation of tasks allocated to different cores.

Understand the increased complexity and cost that comes with multi-core systems:

* High cost of interaction between functions allocated to different cores

* Communication, synchronization and coordination between different cores are more expensive

* Determination of WCET is more complex

Understand that certain approaches that are commonly used in single-core systems
cannot be applied to multi-core systems, e.g. using the priority ceiling
protocol, or disabling interrupts during critical sections. EDF (Earliest
Deadline First) scheduling not optimal.

Know approaches to model multi-core systems  (e.g. using deployment diagram for
multi-core modeling)

Understand the basic of multi-core scheduling

* Static vs. dynamic task allocation with their respective advantages and
disadvantages

Know specific mechanisms used in multi-core systems:

* Spinlocks

* Inter-Processor-Interrupts

Know that using bad core to core communication patterns will have even worse
behavior than single core due (e.g. if there is very high overhead of core to
core communication)

Decide whether multi-core is needed or single core is enough depending on the
estimated workload for the current hardware


[[LG-8-3]]
==== LG 8-3: Basics of distributed embedded systems

Understand the motivation for distributing functionalities across several
control units: proximity to sensors and actuators , independent failure of
different control units can be crucial for achieving safety and reliability
goals

Understand the challenges of distributed systems: Interactions between different
control units have a much higher latency and much lower throughput compared to
local interactions, considering constraints from system integration (e.g. top
down approach), considering real-time constraints

Understand impact of using event triggered vs. using time triggered protocols,
and hybrid solutions in distributed embedded systems (e.g. if the system use
time triggered protocol, what will be the impact on each ECU and how to
synchronize the communication between them)


[[LG-8-4]]
==== LG 8-4: Specifying, modeling and design of distributed systems approach

Motivation: Distributing functionalities of embedded system into several ECUs,
Specifying the communication between ECUs, specifying the constraints on each
ECU, modeling of embedded distributed system.

Challenges: How to standardize the specification and description of distributed
systems, how to model distributed system, how to distribute the real-time
constraints and the communication, how to create system architecture for such
distributed system

Examples of distributed systems specification (e.g. AUTOSAR timing Extension for
automotive embedded distributed systems)

Examples of distributed systems real-time system architecture (e.g.  AUTOSAR
timing extension event chains)

Distributed embedded system communication example (e.g Ethernet network, CAN
network)

// end::EN[]
