=== {learning-goals}

// tag::DE[]
// end::DE[]

// tag::EN[]


[[LG-2-1]]
==== LG 2-1: Modeling Software for Embedded Systems

Participants know different approaches for modeling software for embedded
systems. They understand the basic concepts, strengths and weaknesses of these
approaches:

* UML as a general-purpose modeling language

* UML profiles to adapt UML to a specific domain (e.g., MARTE as a UML profile
  for modeling real-time systems).

* Graphical and textual domain-specific languages (e.g., AADL)

* State machines for modeling reactive systems.

* Modeling data- and signal-flows (e.g., function-block diagrams)

Participants understand how models can be used for analyzing the software, for
example regarding failures, schedulability, error propagation, and latency.

Participants are able to select a suitable modeling approach based on the
requirements and boundary conditions of the system under development.


[[LG-2-2]]
==== LG 2-2: Implementing Software for Embedded Systems

Participants understand how programming languages influence quality
characteristics and cross-cutting concepts:

* Impact of the programming language on analyzability (e.g., with static
  and dynamic analysis tools).

* Impact of the programming language abstractions and concepts for concurrency,
  memory management and error handling on cross-cutting concepts and
  dependability.

Participants know different programming language paradigms (e.g., procedural,
object-oriented, functional). Participants know examples for programming languages
supporting these paradigms that are suitable for embedded systems, and
understand their strengths and weaknesses.


[[LG-2-3]]
==== LG 2-3: Memory Management

Participants understand how memory management strategies and memory-management-related
capabilities of the programming language affect memory safety,
flexibility, predictability, performance and programming complexity:

* Understand the trade-offs in choosing dynamic or static allocation of memory.

* Know managed approaches to dynamically allocated memory (e.g., garbage
  collection, automated reference counting, ownership / non-lexical scoping) and
  their trade-offs.

* Know the impact of system-architectural decisions on memory management (e.g.,
  amount of memory, availability of memory management hardware like an MMU or
  MPU, CPU caches), know software-based approaches to memory safety.

[[LG-2-4]]
==== LG 2-4: Error Handling

Participants know different language features and patterns for error handling
and their strengths and weaknesses, such as return values, global error status
variables, global error handlers, exceptions, monadic error handling (e.g.,
"Result" types, "Either" types).


[[LG-2-5]]
==== LG 2-5: Model-Based Development of Embedded Systems

Participants know how models can be used to generate artifacts for the
realization, and understand the trade-offs:

* Different kinds of models and model elements can be used: structural models
  (e.g., UML component models, AADL) and behavioral models (e.g., statecharts,
  activity diagrams).

* Different kinds artifacts can be generated, e.g. implementation code, test
  cases, configurations, or analysis models.

* Using a model-based approach can have the following benefits:

** Reduced effort since these artifacts do not have to be created manually.

** Increased quality since manual errors can be eliminated.

** Can support adaptibility in a resource-efficient way by resolving variability
   during code generation.

* Using a model-based approach has the following potential costs:

** Creating a sufficiently detailed model requires significant effort, which
   needs to be weighed against the potential savings.

** Generated code often has increased resource demands.

** Potential vendor lock-in, specifically with commercial tools.

** The generated code may be of insufficient quality or not suitable for the
   target platform.

** Using a model-based approach in a safety-critical environment may lead to
   significant tool qualification efforts.



[[LG-2-6]]
==== LG 2-6: Verification of Embedded Software

Participants can explain and give examples for different error categories
(e.g. memory-management errors, synchronization errors, type defects, timing
errors, domain errors).

Participants understand how analysis techniques can be used to detect errors,
and know the limitations of these techniques:

* Participants can define static analysis, understand the difference between
  sound and unsound analysis, and know the application areas of static analysis
  tools. Participants know examples for static analysis tools.

* Participants can define dynamic analysis and know the application areas of
  dynamic analysis tools. Participants know examples for dynamic analysis
  tools.

[[LG-2-7]]
==== LG 2-7: Design Paradigms

Participants know design principles and paradigms for embdded software, such as
design by contract, the robustness principle, or defensive programming.

// end::EN[]
