=== {learning-goals}

// tag::DE[]
// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: Basic Terms and Properties of Real-Time Systems

Participants understand that real-time requirements of embedded systems are the
result of their interaction with the environment.

Participants can explain the difference between timeliness and speed.

Participants can explain the difference between hard/firm real-time requirements
and soft real-time requirements.

Participants understand that all actions along the event chain from the
occurrence of a relevant event to the system reaction must be examined when
implementing real-time requirements (e.g., sensor data read-out, operating-system
context switch, sensor-data processing, actuator control). For hard/firm
real-time requirements, a deadline must be defined for each of these
actions. Missing that deadline is not tolerable.

Participants understand the different types of events (periodic, sporadic,
aperiodic).

Participants understand that real-time architectural design should be performed
early on in the project.

Participants know that real-time architectural design may also encompass
choosing and configuring an operating system, which poses a technological impact
factor.

[[LG-4-2]]
==== LG 4-2: Developing Real-Time Systems

Participants understand the fundamental approach to developing real-time
systems:

* Identify and specify external real-time requirements.

* Choose a time-triggered or event-triggered approach to real-time architectural
  design.

* Identify logical tasks and their properties.

* Identify shared resources required by logical tasks and their properties.

* Map logical tasks to jobs.

* Decide on technical solutions (e.g., RTOS tasks), and allocate jobs to the
  technical solution elements.

* Implement the real-time architectural design.

* Continuously analyze and verify the real-time architectural design and the
  implementation to iteratively refine the real-time architectural design.

Participants know how real-time system design is integrated into the overall
development life cycle.

Participants understand that extending functions or adding new functions at a
later time can have a large impact on time behavior and schedulability. The
degree to which such extensions must be supported is an important impact factor
to real-time architectural design. They understand that real-time affects the
entire life cycle of the system and influences many disciplines and activities
(e.g., requirements elicitation, systems architecture, hardware architecture,
software architecture, software implementation, test and verification,
deployment).

Participants understand that real-time is a cross-cutting concern.


[[LG-4-3]]
==== LG 4-3: Real-Time Requirements

Participants are able to specify and model real-time requirements. They know
different approaches to specifying real-time requirements (e.g., specifying
real-time requirements in UML, SysML, or AADL) and can select a suitable
approach for a particular system.


[[LG-4-4]]
==== LG 4-4: Time-Triggered vs. Event-Triggered Approaches

Participants can describe the time-triggered and event-triggered approaches to
real-time architectural design. They understand the trade-offs of both approaches
regarding determinism and flexibility.

Participants understand that the decision for an approach has a profound,
cross-cutting impact on the architecture and the implementation and is
therefore hard to change.


[[LG-4-5]]
==== LG 4-5: Technical Solutions to Scheduling and Concurrency

Participants can describe technical solutions like cyclic executive, RTOS-based
event-triggered approach, and application-level interrupt handling.

Participants know criteria for deciding between different technical
solutions. They are able to select a technical solution for a specific system and
reasonably justify their decision.

Participants can describe how different technical solutions can be combined (e.g.,
cyclic executive and interrupts).

Participants understand approaches to handling non-periodic events
(interrupt-driven execution, background execution, slack-stealing). They know
further approaches (periodic, deferrable or sporadic server).

Cyclic schedules and frame-based scheduling:

* Participants can describe the benefits and drawbacks of cyclic scheduling.

* Participants can analyze the real-time characteristics of a solution based on
  a cyclic executive.

* Participant can design cyclic schedules for simple real-time problems.

RTOS-based event-triggered approach:

* Participants can describe the differences between static and dynamic
  scheduling methods.

* Participants can describe the advantages and disadvantages of using preemption.

* Participants understand rate-monotonic, deadline-monotonic and
  earliest deadline first scheduling.

* Participants can select an appropriate scheduling approach according to the
  real-time requirements.

* Participants can identify jobs with similar properties and allocate them to
  the same elements of the technical solution (e.g., processes or threads).

* Participants can define the RTOS-tasks and their characteristics.

* Participants can describe important timing properties of RTOSes and hardware
  (e.g., interrupt latency, scheduling latency, dispatch latency)

Application-level interrupt handling:

* Participants understand the strengths and weaknesses of using interrupts at
  the application level.

* Participants can define a concept for using interrupts at the application
  level: prioritizing interrupts, rules for blocking interrupts, using the
  prologue/epilogue model

* Participants understand that the concepts for using interrupts at the
  application level depend on the processor architecture (e.g., number of
  priorities) and the RTOS (e.g., support for prologue/epilogue model).


[[LG-4-6]]
==== LG 4-6: Concurrent Access to Shared Resources

Participants understand the potential problems caused by concurrent access to
shared resources (e.g., blocking time). They understand that whether these
problems can actually occur depends strongly on the chosen technical solution to
concurrency (e.g., time-triggered vs. event-triggered approach).

Participants understand solution approaches for interactions between jobs and
their trade-offs (e.g., message passing, shared data).

Participants know strategies for preventing typical concurrency problems (e.g.,
critical sections, non-preemptive critical sections protocol, semaphores,
synchronization objects and mutexes, atomic actions, non-blocking
synchronization). They can select appropriate strategies for a specific system.

Participants know how to optimize critical sections (e.g., by assigning program
elements which share the same software resources to the same RTOS task).

Participants understand how deadlocks occur and how they can be avoided.

Participants understand priority inversion and know solution approaches (priority
ceiling, priority inheritance).


[[LG-4-7]]
==== LG 4-7: Impact of the Operating System on Real-Time Characteristics

Participants can explain the characteristics of a real-time operating
system. They understand that real-time operating systems and general-purpose
operating systems serve different purposes.

Participants know a minimum of two examples of real-time operating systems and
their characteristics.

Participants can refine the real-time architectural design in the context of the
selected operating system (e.g., refine tasks priorities and assign program
elements to task entities).


[[LG-4-8]]
==== LG 4-8: Real-Time Analysis

Participants know different approaches how the real-time architectural design
can be evaluated, such as design reviews, performing schedulability
analysis, or using tools for scheduling simulation and verification.

Schedulability analysis:

* Participants understand how to gather data on which a schedulability analysis
  can be based (e.g., past experience, measurements, simulation, mathematical
  methods, static analysis).

* Participants know simulation and analytical methods as approaches to gain
  confidence that the real-time requirements can be met.

* Participants understand that the schedulability of a set of tasks cannot be
  shown reliably by individual measurements (e.g., due to blocking time).

* Participants know approaches to schedulability analysis for rate-monotonic,
  deadline-monotonic, or earliest-deadline-first scheduling.

* Participants can apply rate-monotonic analysis to perform a dependable
  schedulability analysis.

* Participants understand the limitations of analytical approaches regarding
  complex real-time systems, due to dependencies among jobs.

* Participants understand simulation as an approach for complex real-time
  systems.

Worst-case execution time (WCET) analysis:

* Participants understand that determining the maximum execution time of a job
  is crucial for real-time analysis. Soundness and tightness are important
  quality characteristics of WCET analysis.

* Participants understand that the precision of WCET analysis is limited. The
  precision is influenced by hardware and software complexity (e.g., impact of
  caches, pipelines, shortest vs. longest program path, memory management,
  dynamic dispatch, approach to error handling).

* Participants can explain advantages, disadvantages and limitations of static
  analysis, dynamic analysis and hybrid approaches to WCET analysis.

* Participants can estimate the overall CPU load to support schedulability
  analyses such as rate-monotonic analysis.

Shared resource analysis:

* Participants understand the difference between WCET and WCRT.

* Participants understand how shared resources and the resource-access protocol
  affect the WCRT. They understand that therefore shared-resource analysis
  needs to be performed as part of real-time analysis.


[[LG-4-9]]
==== LG 4-9: Tools for Real-Time Architectural Design and Analysis

Participants understand that tools for specification, design and analysis of
real-time systems are needed for complex embedded systems with many external
real-time requirements.

Participants know application areas of tools for real-time architectural design
and analysis, such as modeling the real-time architectural design, static WCET
analysis, analytical schedulability analysis, white-box vs. black-box simulation
of real-time systems. Participants know examples of specific tools and their
application areas.


[[LG-4-10]]
==== LG 4-10: Relationship to Distributed and Multi-Core Systems Architectures

Participants understand the challenges introduced when building distributed or
multi-core real-time systems (e.g., proper methods of synchronization, global
scheduling, global time base, latencies imposed by communication).

Participants know different approaches to scheduling (partitioned, clustered,
global scheduling) and migration in multicore systems (e.g., offline vs. online
migration).
// end::EN[]
