=== {learning-goals}


// tag::DE[]
// end::DE[]

// tag::EN[]
[[LG-5-1]]
==== LG 5-1: Foundations of adaptability and variability

Participants understand the motivation and need for adaptability (supporting the
evolution over time, variability in time) and variability (supporting multiple
product variants, variability in space). They understand how the need for
adaptability and variability can be determined and specified.

Participants know possible binding times when variability can be resolved
(before runtime, at startup/load time, at runtime).

Participants know trade-offs and drawbacks of increased adaptability and
variability as well as competing quality goals (e.g., testability, performance,
safety, security and backwards compatibility) and complementing quality goals
(e.g., maintainability, reusability).

Participants know high level approaches to adaptability and variability such as
the 150%-model, 80%-model, product platforms or product lines.

[[LG-5-2]]
==== LG 5-2: Modeling variability in the architecture

Participants understand how the separation between functional architectures and
technical architectures can support adaptability and variability by allowing
alternative technical architectures for the same functional architecture.

Participants understand that variability can occur at the functional level
(e.g., product variants differ in the provided functions) and at the technical
level (e.g., alternative technical solutions exist for the same functionality).

Participants know how to model variation points in requirements, functional
architectures and technical architectures.

[[LG-5-3]]
==== LG 5-3: Supporting adaptability and variability

Participants know how adaptability and variability are supported by:

* principles such as modularity

* architecture and design patterns such as plugin, adapter, facade

* frameworks and libraries

* architecture decisions such as deployment decisions (e.g., edge vs. cloud
  computing)

Participants can apply these solutions to implement variation points in the
architecture.

[[LG-5-4]]
==== LG 5-4: Evolution of embedded systems

Participants understand that adaptability in embedded software is driven both by
requirement changes and by evolution of the systems architecture. This evolution
needs to be addressed in the software architecture and in the development
process.

Participants understand the trade-offs of using legacy code and how its usage
can restrict adaptability and variability.

Participants know how to maintain adaptability and deal with new adaptability
requirements, e.g. by refactoring.

Participants know approaches how to handle system and software updates, as well
as trade-offs of updates.

[[LG-5-5]]
==== LG 5-5: Tools for supporting variability and adaptability

Participants know common tools to model and manage variability.

Participants understand how code generation can support adaptability and
variability and know common tools for code generation.
// end::EN[]
