// (c) iSAQB e.V. (https://isaqb.org)
// ===============================================

[bibliography]
== {references}

// tag::DE[]
// end::DE[]

// tag::EN[]
This section contains references that are cited in the curriculum.
// end::EN[]


**A**

- [[[anastasopoulos, Anastasopoulos+ 2000]]]
Anastasopoulos, M/Gacek, C: Implementing Product Line Variabilities, IESE Report 089.00/E, Fraunhofer IESE

- [[[andreas, Andrews+2008]]]
Jason Andrews, Kamal Hyder, Bob Perrin, Colin Walls, Rick Gentile, Keith E. Curtis, David J. Katz, Jack Ganssle, Jean J. Labrosse, Robert Oshana: Embedded Software, Elsevier, 2008

Jason Andrews, Kamal Hyder, Bob Perrin, Colin Walls, Rick Gentile, Keith E. Curtis, David J. Katz, Jack Ganssle, Jean J. Labrosse, Robert Oshana: 

**B**

- [[[boeckle, Böckle+2004]]]
Böckle, G/Knauber, P/Pohl, K/Schmid, K: Software-Produktlinien – Methoden, Einführung und Praxis, dpunkt.verlag

- [[[boercsoek, Börcsök 2011]]]
Börcsök, J: Funktionale Sicherheit, VDE Verlag

**C**

- [[[clements, Clements+2002]]]
Clements, P/Northrop, L: Software Product Lines – Practices and Patterns, Addison Wesley

**H**

- [[[hanmer, Hanmer 2007]]]
Hanmer, R: Patterns for Fault Tolerant Software, Wiley

- [[[hruschka, Hruschka+2002]]]
Hruschka, P/Rupp, C: Agile Softwareentwicklung für Embedded Real-Time Systems mit der UML, Hanser

**L**

- [[[kang, Kang+1990]]]
Kang, KC et al: Feature Oriented Domain Analysis (FODA) Feasibility Study, Technical Report CMU/SEI-90-TR-21

**I**

- [[[iec61508, IEC 61608]]]
Functional Safety of Electrical/Electronic/Programmable Electronic Safety-Related Systems, 2010

- [[[iso26262, ISO 26262]]]
Road Vehicles - Functional safety, 2011

**L**

- [[[liggesmeyer, Liggesmeyer+2005]]]
Liggesmeyer, P/Rombach, D (ed): Software Engineering eingebetteter Systeme, Elsevier

- [[[linden, Linden+2007]]]
van der Linden, FJ, Schmid, K/Rommes, E: Software Product Lines in Action, Springer

- [[[liu, Liu 2000]]]
Liu, JWS: Real Time Systems, Prentice Hall

**N**

- [[[nasa, NASA 2004]]]
NASA Software Safety Guidebook, NASA-GB-8719.13

- [[[norton, Norton+1997]]]
Norton, S/Dipasquale, M: Threadtime, Prentice Hall

**R**

- [[[rupp, Rupp+2012]]]
Rupp, C et al: UML 2 glasklar, Hanser

**S**

- [[[samek, Samek 2008]]]
Samek, M: Practical Statecharts in C/C++, Butterworth Heinemann

- [[[selic, Selic+1994]]]
Selic, B et al: Real-Time Object-Oriented Modeling, Wiley

- [[[simon, Simon 1999]]]
Simon, D: An Embedded Software Primer, Addison Wesley

- [[[smith, Smith+2011]]]
Smith, D/Simpson, K: Safety Critical Systems Handbook, Butterworth Heinemann

- [[[stallings, Stallings 2014]]]
Stallings, W: Operating Systems: Internals and Design Principles, Prentice Hall

**W**

- [[[wolf, Wolf 2007]]]
Wolf, W: High Performance Embedded Computing, Morgan Kaufmann
